name: card_security_system
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  flutter_speed_dial: ^6.2.0
  provider: ^6.0.5
  credit_card_scanner: ^1.0.5
  credit_card_type_detector: ^2.0.0
  credit_card_validator: ^2.0.1
  http: ^0.13.4
  hive: ^2.2.2
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  hive_generator: 
  hive_test: ^1.0.1
  auto_route_generator: 

flutter:
  uses-material-design: true
