name: card_security_system
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  flutter_speed_dial: ^6.2.0
  provider: ^6.0.5
  credit_card_scanner: ^1.0.5
  credit_card_type_detector: 
  credit_card_validator: ^2.0.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
